// Tipo Number

const meuNumero = 3;

const primeiroNumero = 1;
const segundoNumero = 2;

const operacaoMatematica = primeiroNumero + segundoNumero;

console.log(operacaoMatematica)

// ponto flutuante 

const numeroPontoFlutuante =3.3;
const pontoFlutuanteSemZero =.5;

const novaOperaçao = primeiroNumero / 
numeroPontoFlutuante;

console.log(novaOperaçao)

// NaN -> Not a Number ( não é um numero )

const alura = "Alura";
console.log(alura * primeiroNumero)
